export const EMAILJS = {
  SERVICE_ID: process.env.NEXT_PUBLIC_EMAIL_SERVICE_ID,
  TEMPLATE_ID_FOR_USER: process.env.NEXT_PUBLIC_EMAIL_TEMPLATE_ID_FOR_USER,
  TEMPLATE_ID_FOR_ME: process.env.NEXT_PUBLIC_EMAIL_TEMPLATE_ID_FOR_ME,
  USER_ID: process.env.NEXT_PUBLIC_EMAIL_USER_ID,
};